apiVersion: apps/v1
kind: Deployment
metadata:
  name: amena-web-frontend
spec:
  selector:
    matchLabels:
      app: amena-web-frontend
  template:
    metadata:
      labels:
        app: amena-web-frontend
    spec:
      nodeSelector:
        nodeGroup: default
      containers:
      - name: amena-web-frontend
        image: 828752933783.dkr.ecr.ap-northeast-1.amazonaws.com/amena-web-frontend:0.0.6
        env:
          - name: NODE_ENV
            value: production
          - name: AMENA_API_PATH
            value: http://amena-web-backend-service:80
---
apiVersion: v1
kind: Service
metadata:
  name: amena-web-frontend-service
spec:
  selector:
    app: amena-web-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: amena-web-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: amena-web-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70